after_training: null
agent: tonic.torch.agents.PPO()
before_training: null
checkpoint: last
environment: tonic.environments.Gym("BipedalWalker-v3")
environment_name: null
header: import tonic.torch
name: PPO-X
parallel: 1
path: null
seed: 0
sequential: 1
test_environment: null
trainer: null
